apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-1
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: sample-1
        image: devopsprosamples/next-sample-1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: sample-1
spec:
    type: ClusterIP
    selector:
      app: nginx
    ports:
      - protocol: TCP
        port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress

spec:
  rules:
  - host: "sample-1.devopspro.in"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sample-1
            port:
              number: 3000

